#!/bin/bash
#
# Configure ComputeFleet node to use shared NCCL installation
# This script runs on ComputeFleet nodes
#
# Usage: use-shared-nccl.sh <shared_dir>
# Example: use-shared-nccl.sh /fsx

set -e

SHARED_DIR="${1:-/fsx}"
NCCL_INSTALL_DIR="${SHARED_DIR}/nccl"
NCCL_VERSION_FILE="${NCCL_INSTALL_DIR}/.nccl_version"
NCCL_ENV_SCRIPT="${NCCL_INSTALL_DIR}/setup-nccl-env.sh"

echo "=========================================="
echo "Configuring Shared NCCL on ComputeFleet"
echo "=========================================="
echo "Shared Directory: ${SHARED_DIR}"
echo "NCCL Directory: ${NCCL_INSTALL_DIR}"
echo "=========================================="

# Check if shared directory exists
if [ ! -d "${SHARED_DIR}" ]; then
    echo "✗ Error: Shared directory ${SHARED_DIR} does not exist"
    echo "  NCCL cannot be configured"
    exit 1
fi

# Wait for NCCL installation to complete (in case HeadNode is still installing)
MAX_WAIT=300  # 5 minutes
WAIT_COUNT=0
while [ -f "${NCCL_INSTALL_DIR}/.installing" ]; do
    if [ $WAIT_COUNT -ge $MAX_WAIT ]; then
        echo "✗ Timeout waiting for NCCL installation on HeadNode"
        exit 1
    fi
    echo "⏳ Waiting for NCCL installation to complete on HeadNode... ($WAIT_COUNT/$MAX_WAIT seconds)"
    sleep 5
    WAIT_COUNT=$((WAIT_COUNT + 5))
done

# Check if NCCL is installed
if [ ! -f "${NCCL_VERSION_FILE}" ]; then
    echo "✗ Error: NCCL not found in shared storage"
    echo "  Expected location: ${NCCL_INSTALL_DIR}"
    echo "  Please ensure NCCL is installed on HeadNode first"
    exit 1
fi

NCCL_VERSION=$(cat "${NCCL_VERSION_FILE}")
echo "✓ Found NCCL installation: ${NCCL_VERSION}"

# Check if environment setup script exists
if [ ! -f "${NCCL_ENV_SCRIPT}" ]; then
    echo "✗ Error: NCCL environment script not found"
    echo "  Expected: ${NCCL_ENV_SCRIPT}"
    exit 1
fi

# Source the NCCL environment
echo "Configuring NCCL environment..."
source "${NCCL_ENV_SCRIPT}"

# Add NCCL environment to system profile
PROFILE_SCRIPT="/etc/profile.d/nccl-shared.sh"
cat > "${PROFILE_SCRIPT}" << EOF
# Shared NCCL configuration
# Auto-generated by use-shared-nccl.sh
source ${NCCL_ENV_SCRIPT}
EOF

chmod +x "${PROFILE_SCRIPT}"

# Verify NCCL libraries are accessible
echo ""
echo "Verifying NCCL installation..."
if ldconfig -p | grep -q libnccl; then
    echo "✓ NCCL libraries found in system"
    ldconfig -p | grep libnccl | head -3
else
    echo "⚠️  Warning: NCCL libraries not found in ldconfig cache"
    echo "   Running ldconfig..."
    ldconfig
fi

echo ""
echo "=========================================="
echo "✓ Shared NCCL Configuration Complete"
echo "=========================================="
echo "NCCL Version: ${NCCL_VERSION}"
echo "Environment Script: ${NCCL_ENV_SCRIPT}"
echo "Profile Script: ${PROFILE_SCRIPT}"
echo ""
echo "NCCL is ready to use on this compute node"
echo "=========================================="
